### ISSUE TITLE
how to install nclRshiny

### ISSUE THREAD

**Issue by hliu2016** [rcourses/nclRshiny#1]
Hi, I tried to install nclRshiny via the R command:
`install.packages("nclRshiny", repos="https://github.com/rcourses/nclRshiny")`

However, it can not be installed because of the following error:

> Installing package into ‘C:/Users/hliu/Documents/R/win-library/3.4’
> (as ‘lib’ is unspecified)
> Warning in install.packages :
>   unable to access index for repository https://github.com/rcourses/nclRshiny/src/contrib:
>   cannot open URL 'https://github.com/rcourses/nclRshiny/src/contrib/PACKAGES'
> Warning in install.packages :
>   package ‘nclRshiny’ is not available (for R version 3.4.3)
> Warning in install.packages :
>   unable to access index for repository https://github.com/rcourses/nclRshiny/bin/windows/contrib/3.4:
>   cannot open URL 'https://github.com/rcourses/nclRshiny/bin/windows/contrib/3.4/PACKAGES'
  
Could you help me?

**Comment by csgillespie** [comment]
Sorry, this package is an old package used for teaching. It's about to be deleted (in the next day or so) as it's out of date and not used.

Sorry
